---
title: "Assignment 1"
output:
  html_document:
    toc: true
    number_sections: true
author: "by: Siard van den Bosch"
bibliography: references.bib
---
  
  
```{r, install remotely, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
# install.packages("remotes")
# remotes::install_github("rlesur/klippy")
``` 

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```



----
  # Start of the tutorial
  
  ## A.3
  
```{r}

# start with clean workspace
rm(list = ls())

# install.packages I will need later here
# install.packages("installr")  #you  first install packages
require(installr)  #then you will need to load them. This package is used to simply update R
# install.packages("foreign")
require(foreign)  #used to read in spss data files
# install.packages("tidyverse", dependencies = TRUE)
require(tidyverse)
require(installr)  #then you will need to load them. This package is used to simply update R
# install.packages("haven", dependencies = TRUE)
# install.packages("labelled", dependencies = TRUE)
# install.packages("mice", dependencies = TRUE)
library(haven)
library(tidyverse)
library(labelled)
library(mice)
# update if necessarry. Best to run this command in RGui, not in RStudio.
# updateR()

# define workdirectory, note the double backslashes
# setwd(dirname(rstudioapi::getSourceEditorContext()$path))
```

## A.5

```{r}
tesvariable <- 4
ls()

#> [1] "colorize"    "tesvariable"

list = ls()
list
#> [1] "colorize"    "tesvariable"
ls()
#> [1] "colorize"    "list"        "tesvariable"
rm(list)
ls()
#> [1] "colorize"    "tesvariable"
# ? :-)
rm(list = ls())
ls()
#> character(0)
```
## A.6

```{r}

cv08 <- foreign::read.spss("Cultural_Changes_2008.sav", use.value.labels = T, to.data.frame = T)
cv10 <- foreign::read.spss("Cultural_Changes_2010.sav", use.value.labels = T, to.data.frame = T)

# normally I think setting use.value.labels=F is more convenient. Thus lets load the data again but
# now without labels
cv08_nolab <- foreign::read.spss("Cultural_Changes_2008.sav", use.value.labels = F, to.data.frame = T)
cv10_nolab <- foreign::read.spss("Cultural_Changes_2010.sav", use.value.labels = F, to.data.frame = T)

# finally, import the data using haven
cv08_haven <- haven::read_spss("Cultural_Changes_2008.sav")
cv10_haven <- haven::read_spss("Cultural_Changes_2010.sav")

str(cv08)
str(cv08_nolab)
str(cv08_haven)

str(cv08$lftop)
str(cv08_nolab$lftop) 
str(cv08_haven$lftop)  # a 'dbl+lbl' this stands for doubles, or real numbers, which are labeled
# next to the data itself, attributes are stored
attributes(cv08$lftop)
attributes(cv08_nolab$lftop)
# to access specific attributes
attr(cv08_haven$lftop, "labels")
summary(cv08$lftop)
summary(cv08_nolab$lftop)
table(cv08_haven$lftop, useNA = "always")

names(cv08_haven)
# summary(cv08_haven)
head(cv08_haven)

# fix(cv08)
# View(cv08_haven)

```
#A7

## A.7.1

```{r}
str(cv08_haven$lftop)
summary(cv08_haven$lftop)
attr(cv08_haven$lftop, "labels")
table(cv08_haven$lftop, useNA = "always")

cv08$lftop_new <- cv08$lftop
cv08$lftop_new[cv08$lftop_new == "Onbekend"] <- NA
table(cv08$lftop_new, useNA = "always")
levels(cv08$lftop_new)
str(cv08$lftop_new)

cv08$agen <- as.numeric(as.character(cv08$lftop_new))  #how clumsy. we first convert the factor to a string and then to a numeric variable. 
table(cv08$agen, useNA = "always")
str(cv08$agen)


```

## A7.2

```{r}
# fix(cv08_haven)
# View(cv08_haven)

cv08_haven <- mutate(cv08_haven, lftop_new = lftop)
cv08_haven$lftop_new <- na_if(cv08_haven$lftop_new, 99)
cv08_haven <- mutate(cv08_haven, lftop_new = na_if(lftop, 99))
table(cv08_haven$lftop_new, useNA = "always")
```
#A8

## A8.1

```{r}
levels(cv08$var006n)
table(cv08$var006n, useNA = "always")

# lets make it a numeric var first
cv08$educn <- as.numeric(cv08$var006n)
# check
table(cv08$educn, useNA = "always")

# start with an empty variable
cv08$educ3 <- NA
# fill category by category
cv08$educ3[cv08$educn == 2 | cv08$educn == 3] <- 1
cv08$educ3[cv08$educn > 3 & cv08$educn < 8] <- 2
cv08$educ3[cv08$educn > 7 & cv08$educn < 11] <- 3

# check
table(cv08$educ3, useNA = "always")
prop.table(table(cv08$educ3, useNA = "always"))

# now educ3 is a numeric variable, we want it as factor
cv08$educ3 <- as.factor(cv08$educ3)
table(cv08$educ3, useNA = "always")

```

## A8.2

```{r}
# install.packages('labelled')
require(labelled)  #to be able to use the recode function on haven labelled variables

# inspect variable
str(cv08_haven$var006n)
attr(cv08_haven$var006n, "labels")
table(cv08_haven$var006n, useNA = "always")

# recode values, all missings as one value
cv08_haven <- mutate(cv08_haven, educ3 = recode(var006n, `-3` = -9, `-1` = 1, `1` = 1, `2` = 2, `3` = 2,
                                                `4` = 2, `5` = 2, `6` = 3, `7` = 3, `8` = 3, `10` = -9), .keep_value_labels = FALSE)

# replace missing values with NA.
cv08_haven <- mutate(cv08_haven, educ3 = na_if(educ3, -9))

# make educ3 a factor
cv08_haven <- mutate(cv08_haven, educ3 = factor(educ3, levels = c(1, 2, 3), labels = c("primary", "secondary",
                                                                                       "tertiary")))

# check
table(cv08_haven$educ3, useNA = "always")

#Tidiest way
cv08_haven <- cv08_haven %>%
  mutate(educ3 = recode(var006n, `-3` = -9, `-1` = 1, `1` = 1, `2` = 2, `3` = 2, `4` = 2, `5` = 2,
                        `6` = 3, `7` = 3, `8` = 3, `10` = -9, .keep_value_labels = FALSE), educ3 = na_if(educ3, -9),
         educ3 = factor(educ3, levels = c(1, 2, 3), labels = c("primary", "secondary", "tertiary")))

```

# A9

## A9.1

```{r}
summary(cv08$int055)
summary(cv08$int056)
summary(cv08$int057)

cv08$int055n <- as.numeric(cv08$int055)
table(cv08$int055n, useNA = "always")
cv08$int056n <- as.numeric(cv08$int056)
table(cv08$int056n, useNA = "always")
cv08$int057n <- as.numeric(cv08$int057)
table(cv08$int057n, useNA = "always")

cv08$int055n[cv08$int055n < 5] <- NA
cv08$int055n <- cv08$int055n - 4
cv08$int056n[cv08$int056n < 5] <- NA
cv08$int056n <- cv08$int056n - 4
cv08$int057n[cv08$int057n < 5] <- NA
cv08$int057n <- cv08$int057n - 4

testmeans <- rowMeans(cbind(cv08$int055n, cv08$int056n, cv08$int057n), na.rm = T)
head(testmeans) 

# lets first count how many missings we have for each respondent
nmis <- rowSums(is.na(cbind(cv08$int055n, cv08$int056n, cv08$int057n)))

# ?is.na ?rowSums

testmeans <- ifelse(nmis < 2, testmeans, NA)

# add the calculated means to our dataset
cv08$int_mean <- testmeans

# Bonus: count specific values so now we have this, it is easy to find how many times respondents
# answered 'zeer groot', that is '1' timesZG <- rowSums(cbind(cv08$int055n, cv08$int056n,
# cv08$int057n)==1, na.rm=T)

```

## A9.2

```{r}
# Step 1: have a look at the vars
str(cv08_haven$int055)
attr(cv08_haven$int055, "labels")
summary(cv08_haven$int055)
summary(cv08_haven$int056)
summary(cv08_haven$int057)

table(cv08_haven$int055n, useNA = "always")
table(cv08_haven$int056, useNA = "always")
table(cv08_haven$int057, useNA = "always")

# Step 2: define missings and recode
cv08_haven <- mutate(cv08_haven, int055n = recode(int055, `-6` = -9, `-5` = -9, `-3` = -9, `-2` = -9,
                                                  `1` = 4, `2` = 3, `3` = 2, `4` = 1), .keep_value_labels = FALSE) %>%
  mutate(int055n = na_if(int055n, -9)) %>%
  mutate(int055n = labelled(int055n, c(`Helemaal geen tegenstelling` = 1, `Niet zo groot` = 2, Groot = 3,
                                       `Zeer groot` = 4)))

cv08_haven <- mutate(cv08_haven, int056n = recode(int056, `-6` = -9, `-5` = -9, `-3` = -9, `-2` = -9,
                                                  `1` = 4, `2` = 3, `3` = 2, `4` = 1), .keep_value_labels = FALSE) %>%
  mutate(int056n = na_if(int056n, -9)) %>%
  mutate(int056n = labelled(int056n, c(`Helemaal geen tegenstelling` = 1, `Niet zo groot` = 2, Groot = 3,
                                       `Zeer groot` = 4)))

cv08_haven <- mutate(cv08_haven, int057n = recode(int057, `-6` = -9, `-5` = -9, `-3` = -9, `-2` = -9,
                                                  `1` = 4, `2` = 3, `3` = 2, `4` = 1), .keep_value_labels = FALSE) %>%
  mutate(int057n = na_if(int057n, -9)) %>%
  mutate(int057n = labelled(int057n, c(`Helemaal geen tegenstelling` = 1, `Niet zo groot` = 2, Groot = 3,
                                       `Zeer groot` = 4)))


# Step 3: calculate means.  option 1
cv08_haven <- cv08_haven %>%
  rowwise() %>%
  mutate(int_mean = mean(c(int055n, int056n, int057n), na.rm = TRUE))


## option 2
cv08_haven <- cv08_haven %>%
  mutate(int_mean = rowMeans(cbind(int055n, int056n, int057n), na.rm = TRUE))

# Mean with at most 1 NA in the three variables

cv08_haven <- cv08_haven %>%
  mutate(int_mean_temp = rowMeans(cbind(int055n, int056n, int057n), na.rm = TRUE), nmis = rowSums(is.na(cbind(int055n,
                                                                                                              int056n, int057n))), int_mean = ifelse(nmis < 2, int_mean_temp, NA)) %>%
  select(-int_mean_temp, -nmis)
```

# A10

## A10.1

```{r}
# step 1: selecting the variables you want to keep. for this tutorial only 6 variables: id, age,
# sex, educ, health, region
cv08_sel <- cv08[, c("we_id", "lftop", "geslacht", "var006n", "v401", "landd")]
cv10_sel <- cv10[, c("Sleutel", "var002", "var001", "Vltoplop", "V401", "Landd")]

# step 2: making the variables similar across individual datasets step 2a: making names the same
names(cv08_sel) <- names(cv10_sel) <- c("id", "age", "sex", "educ", "health", "region")

# step 2b: making levels and labels consistent
# summary(cv08_sel)
# summary(cv10_sel)
# they look very consistent already. but check carefully.

# we don't want id to be a factor but numeric. Note that we don't want the factor level values as
# numbers but the actual labels as numbers.

# id
cv08_sel$id <- as.numeric(as.character(cv08_sel$id))
cv10_sel$id <- as.numeric(as.character(cv10_sel$id))

# age
cv08_sel$age <- as.numeric(as.character(cv08_sel$age))
cv10_sel$age <- as.numeric(as.character(cv10_sel$age))

# sex men
levels(cv08_sel$sex)
levels(cv10_sel$sex)
table(cv08_sel$sex, useNA = "always")
table(cv10_sel$sex, useNA = "always")
# lets make it a numeric var first
cv08_sel$sexn <- as.numeric(cv08_sel$sex)
table(cv08_sel$sexn)
# recode into dummy
cv08_sel$men <- ifelse(cv08_sel$sexn == 2, 1, 0)
cv08_sel$men <- ifelse(cv08_sel$sexn == 1, NA, cv08_sel$men)
# check
table(cv08_sel$men, useNA = "always")
# lets make it a numeric var first
cv10_sel$sexn <- as.numeric(cv10_sel$sex)
table(cv10_sel$sexn)
# recode into dummy
cv10_sel$men <- ifelse(cv10_sel$sexn == 2, 1, 0)
# check
table(cv10_sel$men, useNA = "always")

# educ educ3
levels(cv08_sel$educ)
levels(cv10_sel$educ)
table(cv08_sel$educ, useNA = "always")
table(cv10_sel$educ, useNA = "always")
# lets make it a numeric var first
cv08_sel$educn <- as.numeric(cv08_sel$educ)
table(cv08_sel$educn)
# recode into 3cats: 1 primair, 2 secundair, 3 is tertiair
cv08_sel$educ3 <- NA
cv08_sel$educ3[cv08_sel$educn == 2 | cv08_sel$educn == 3] <- 1
cv08_sel$educ3[cv08_sel$educn > 3 & cv08_sel$educn < 8] <- 2
cv08_sel$educ3[cv08_sel$educn > 7 & cv08_sel$educn < 11] <- 3
# check
table(cv08_sel$educ3, useNA = "always")
prop.table(table(cv08_sel$educ3, useNA = "always"))

# lets make it a numeric var first
cv10_sel$educn <- as.numeric(cv10_sel$educ)
table(cv10_sel$educn)
# recode into 3cats: 1 primair, 2 secundari, 3 is tertiair
cv10_sel$educ3 <- NA
cv10_sel$educ3[cv10_sel$educn < 3] <- 1  #correct?
cv10_sel$educ3[cv10_sel$educn > 2 & cv10_sel$educn < 6] <- 2
cv10_sel$educ3[cv10_sel$educn == 6] <- 3
# check
table(cv10_sel$educ3, useNA = "always")
prop.table(table(cv10_sel$educ3, useNA = "always"))

# Merging
# lets add a wave variable
cv08_sel$wave <- 2008
cv10_sel$wave <- 2010

# let make a fake ID, we will use this later when we pretend CV is panel data.
cv08_sel$id2 <- rank(cv08_sel$id)
cv10_sel$id2 <- rank(cv10_sel$id)

# simply place one dataset under the other thus row bind (rbind) check first if same vars in both
# datasets. perhaps clean up first.

cv08_sel <- cv08_sel[, c("id", "id2", "age", "men", "educ3", "health", "region", "wave")]
cv10_sel <- cv10_sel[, c("id", "id2", "age", "men", "educ3", "health", "region", "wave")]

# summary(cv08_sel)

cv_tot <- rbind(cv08_sel, cv10_sel)
# summary(cv_tot)

# lets make a panel dataset in wide format
cv_tot_panel <- merge(cv08_sel, cv10_sel, all = TRUE, by = "id2")
head(cv_tot_panel)

# rename variables. and when necessary merge again with third wave. not very efficient but it
# works.

# many people prefer the reshape function. (i like doing it myself but here it goes)
cv_tot_panel <- reshape(cv_tot, timevar = "wave", idvar = "id2", direction = "wide")
head(cv_tot_panel)


```

## A10.2

```{r}
# step 1: selecting the variables you want to keep. for this tutorial only 6 variables: id, age,
# sex, educ, health, region 
cv08_sel <- cv08_haven %>%
  select(c("we_id", "lftop", "geslacht", "var006n", "v401", "landd"))

cv10_sel <- cv10_haven %>%
  select(c("Sleutel", "var002", "var001", "Vltoplop", "V401", "Landd"))

# step 2: making the variables similar across individual datasets step 2a: making names the same
names(cv08_sel) <- names(cv10_sel) <- c("id", "age", "sex", "educ", "health", "region")

# step 2b: making levels and labels consistent
str(cv08_sel)
str(cv10_sel)

# summary(cv08_sel) summary(cv10_sel)

# they look very consistent already. but check carefully.  id is okay

# age: replace 'onbekend'
cv08_sel <- cv08_sel %>%
  mutate(age = na_if(age, 99))
cv10_sel <- cv10_sel %>%
  mutate(age = na_if(age, 99))

# sex: men
cv08_sel <- cv08_sel %>%
  mutate(men = recode(sex, `9` = -9, M = 1, V = 0, .keep_value_labels = FALSE), men = na_if(men, -9),
         men = labelled(men, c(man = 1, vrouw = 0)))
cv10_sel <- cv10_sel %>%
  mutate(men = recode(sex, `2` = 0, .keep_value_labels = FALSE), men = labelled(men, c(man = 1, vrouw = 0)))

# educ educ3
attr(cv08_sel$educ, "labels")
attr(cv10_sel$educ, "labels")

cv08_sel <- cv08_sel %>%
  mutate(educ3 = recode(educ, `-3` = -9, `-1` = 1, `1` = 1, `2` = 2, `3` = 2, `4` = 2, `5` = 2, `6` = 3,
                        `7` = 3, `8` = 3, `10` = -9, .keep_value_labels = FALSE), educ3 = na_if(educ3, -9), educ3 = factor(educ3,
                                                                                                                           levels = c(1, 2, 3), labels = c("primary", "secondary", "tertiary")))

cv10_sel <- cv10_sel %>%
  mutate(educ3 = recode(educ, `-1` = 1, `1` = 1, `2` = 2, `3` = 2, `4` = 2, `5` = 3, `10` = -9, .keep_value_labels = FALSE),
         educ3 = na_if(educ3, -9), educ3 = factor(educ3, levels = c(1, 2, 3), labels = c("primary", "secondary",
                                                                                         "tertiary")))

# lets add a wave variable
cv08_sel$wave <- 2008
cv10_sel$wave <- 2010

# let make a fake ID, we will use this later when we pretend CV is panel data.
cv08_sel$id2 <- rank(cv08_sel$id)
cv10_sel$id2 <- rank(cv10_sel$id)

# simply place one dataset under the other thus row bind (rbind) check first if same vars in both
# datasets. perhaps clean up first.

cv08_sel <- cv08_sel %>%
  select(c("id", "id2", "age", "men", "educ3", "health", "region", "wave"))

cv10_sel <- cv10_sel %>%
  select(c("id", "id2", "age", "men", "educ3", "health", "region", "wave"))

cv_tot_tidy <- cv08_sel %>%
  add_row(cv10_sel)

# summary(cv_tot_tidy)
head(cv_tot_tidy)

# lets make a panel dataset in wide format
cv_tot_panel_tidy <- full_join(cv08_sel, cv10_sel, by = "id2", suffix = c(".2008", ".2010"))
# summary(cv_tot_panel_tidy)
```

# A11

## A11.1

```{r}
# step 1. construct dataset with aggregate info
age_region <- aggregate(cv_tot$age, by = list(cv_tot$region), FUN = mean)
head(age_region)

# step 1. construct dataset with aggregate info
age_region <- aggregate(cv_tot$age, by = list(cv_tot$region), FUN = mean, na.rm = TRUE)
head(age_region)

# lets correct variable names
names(age_region) <- c("region", "age_region")
age_region

# step 2. match to dataset
cv_total <- merge(cv_tot, age_region, by = "region", all.x = TRUE)
head(cv_total)
tail(cv_total)

# You can also define your own functions and use these.

fmean_narm <- function(x) {
  mean(x, na.rm = T)
}

age_region_test <- aggregate(cv_tot$age, by = list(cv_tot$region), FUN = fmean_narm)
head(age_region_test)

```

## 11.2

```{r}
# step 1. convert the dataset to an aggregate/grouped version using the 'group_by' function from
# the Dplyr package (part of the tidyverse), which will enable you to perform aggregate-level, or
# 'by group,' operations.
age_region <- group_by(cv_tot_tidy, region)

# step 2. use mutate to create and append the mean age by region to the original data frame (don't
# forget to remove NA values).
age_region <- mutate(age_region, mean = mean(age, na.rm = TRUE))

# step 3. you can link both commands using the pipe operator %>% to keep your code concise (and
# readable if you're writing a script).
cv_total_tidy <- cv_tot_tidy %>%
  group_by(region) %>%
  mutate(age_region = mean(age, na.rm = TRUE)) %>%
  ungroup()  #because group_by() returns a grouped tibble (a tibble specific class with a group attribute), it's good practice to close the pipe-chain with ungroup() to avoid an errors down the line. 
```

# A12

## A12.1

```{r}
model1 <- lm(as.numeric(health) ~ men + age + as.factor(educ3) + as.factor(region), data = cv_total)
summary(model1)

cv_total$health[cv_total$health == "Weigert"] <- NA
cv_total$healthn <- as.numeric(cv_total$health) - 4
table(cv_total$health, useNA = "always")
table(cv_total$healthn, useNA = "always")

# Option 1: listwise deletion
# step 1. define all missings
# summary(cv_total)

model2 <- lm(as.numeric(healthn) ~ men + age + as.factor(educ3) + as.factor(region), data = cv_total)
summary(model2)

# Option 2: replacing missing values.
cv_total$men2 <- ifelse(is.na(cv_total$men), 2, cv_total$men)
summary(cv_total$men2)

cv_total$educ3b <- ifelse(is.na(cv_total$educ3), 4, cv_total$educ3)
summary(cv_total$educ3b)

cv_total$age2 <- ifelse(is.na(cv_total$age), mean(cv_total$age, na.rm = TRUE), cv_total$age)
# And lets make a dummy that indicates for whom we replaced missing values.
cv_total$age_mis <- ifelse(is.na(cv_total$age), 1, 0)
summary(cv_total$age2)
table(cv_total$age_mis)

# pay attention, now use categorical variable men2
model3 <- lm(healthn ~ as.factor(men2) + age2 + age_mis + as.factor(educ3b) + as.factor(region), data = cv_total)
summary(model3)

# Option 3: impute missing values
# lets start with the original dataset, that is without replacement of the missings
cv_total <- cv_total[, c("id", "id2", "age", "men", "educ3", "health", "region", "wave")]
# define all missings only for health needs to be redefined
cv_total$health[cv_total$health == "Weigert"] <- NA
cv_total$health <- as.numeric(cv_total$health) - 4

# multiple imputation take into account measurement level of variables
cv_total$men <- as.factor(cv_total$men)
cv_total$educ3 <- as.factor(cv_total$educ3)

# check pattern
md.pattern(cv_total)

# we do not have real patterns. thus MCAR. This is only seldom the case!!

# lets impute
names(cv_total)

# We do not want to use id id2 and wave to predict the other variables thus we need to tell mice in
# the predictorMatrix argument. Easiest way is to first estimate and then correct.

imp <- mice(data = cv_total, method = c("", "", "cart", "logreg", "polr", "cart", "", ""))
attributes(imp)
pred <- imp$pred
pred[, "id"] <- 0
pred[, "id2"] <- 0
pred[, "wave"] <- 0
pred

# let us also use a seed, so we have the same data in class.
imp <- mice(data = cv_total, method = c("", "", "cart", "logreg", "polr", "cart", "", ""), pred = pred,
            seed = 45622)

# summary(cv_total)
summary(complete(imp))

plot(imp)

# and fit model on imputed dataset
model_imp <- with(imp, lm(as.numeric(health) ~ men + age + educ3 + region))
pool_model_imp <- pool(model_imp)
summary(pool_model_imp)

```

## A12.2

```{r}
model1 <- cv_total_tidy %>%
  mutate(healthn = as.numeric(health), across(c(educ3, region), as.factor)) %>%
  lm(formula = healthn ~ men + age + educ3 + region) %>%
  summary(model1)
# the across function from the Dplyr package is similar to the apply function (if MARGIN = 2) from
# base R. it performs the same operation on multiple columns (or, if you have groups, for each
# combination of columns and groups).

# lm is not a 'pipe friendly' function because the data is provided in the second argument, while
# the pipe operator reads the data from the first unnamed(!) argument that follows the %>%. by
# naming the first argument, the pipe will take data from the second argument, which is (in this
# case) the correct data argument.

# step 1. define all missings

cv_total_tidy <- cv_total_tidy %>%
  mutate(health = na_if(health, -2), healthn = as.numeric(health) - 4)

# option 1: listwise deletion

model2 <- cv_total_tidy %>%
  mutate(across(c(educ3, region), as.factor)) %>%
  lm(formula = healthn ~ men + age + educ3 + region) %>%
  summary(model2)

# option 2: replacing missing values

# with the first mutate argument you avoid repeating as.numeric() for each variable.
cv_total_tidy2 <- cv_total_tidy %>%
  mutate(across(everything(), as.numeric), men2 = replace_na(men, 2), educ3b = replace_na(educ3, 4),
         age2 = replace_na(age, mean(age, na.rm = TRUE)), age_mis = ifelse(is.na(age), 1, 0))

# note: the following two commands are equivalent: mutate(across(everything(), as.numeric))
# mutate_all(as.numeric) the next two as well: mutate_at(c('men2', 'educ3b', 'region'), as.factor)
# mutate(across(c(men2, educ3b, region), as.factor))

# pay attention, now use categorical variable men2.
model3 <- cv_total_tidy2 %>%
  mutate_at(c("men2", "educ3b", "region"), as.factor) %>%
  lm(formula = healthn ~ men2 + age2 + age_mis + educ3b + region) %>%
  summary(model3)

# option 3: imputing missing values

pred <- cv_total_tidy  %>%
  select(c("id", "id2", "age", "men", "educ3", "health", "region", "wave")) %>% #start with the original variables.
  mutate_all(as.numeric)  %>%
  mutate_at(c("men", "educ3"), as.factor) %>%
  mice(method = c("", "", "cart", "logreg", "polr", "cart", "", "")) %>%
  unclass() %>% #The object returned from the mice function is of class 'mids,' which dplyr's functions cannot handle. The unclass() function from base R solve this issue as it removes the class attribute and, in this case, returns a list that dplyr can handle.
  pluck("predictorMatrix") %>% #the pluck() function from the Purrr package (part of the tidyverse) is the user-friendly equivalent of `[[` in base R: `[[`("predictorMatrix"), which enables you to extract a single element from the list we just created using unclass().
  as.data.frame() %>% #Because the mutate function (and its variations) are not build for lists, we need to coerce into a data frame (or Tibble)
  mutate_at(c("id", "id2", "age"), funs(recode(1, 0))) %>% #To 'remove' the columns id id2 and wave as predictors, we recode all their 1s to 0s using mutate_at() and recode().
  as.matrix()


#impute missings (again but now on correct predictors) and fit model on imputed dataset

model_imp <- cv_total_tidy %>%
  select(c("id","id2","age","men","educ3","health","region","wave")) %>%
  mutate_all(as.numeric)  %>%
  mutate_at(c("men", "educ3"), as.factor) %>%
  mice(method = c("", "", "cart", "logreg", "polr", "cart", "", ""), pred = pred, seed = 45622) %>%
  with(lm(as.numeric(health) ~ men + age + educ3 + region)) %>%
  pool()

summary(model_imp)
```

# A14

```{r, eval=FALSE}
CSR <- read.spss("CSR_teaching-data.sav", use.value.labels = T, to.data.frame = T)

summary(S020)
summary(S002)
summary(S003)

select_if(c(S003 == 840))
table(S002, S003)

summary(A029, A030, A032, A034, A035, A038, A039, A041, A042, X003, X011, X002)

countsocialvalue <- A029+A030+A032+A034+A035+A038+A039+A041+A042
summary(countsocialvalue)

table(S002, countsocialvalue)

summary(D054, D057, D059, D060, C001)

alpha(D059, D060)

summary(X002)
Turning18 <- (X002 + 18)
summary(Turning18)

CSR <- CSR_teaching-data[, c("gendernorms", "female", "age", "relig_dummy", "YoS1995", "YoS1999", "YoS2006", "YoS2017", "livingtogether", "paidwork", "Turning18)]
CNTR <- Country unemployment[, c("Turning18", "CNTRYunemployment")]

data_tot <- rbind(CSR, CNTR)
# summary(data_tot)

# many people prefer the reshape function. (i like doing it myself but here it goes)
cv_tot_panel <- reshape(cv_tot, timevar = "S002", idvar = "id2", direction = "wide")
head(cv_tot_panel)

Gendernorms <-- (D059 + D060 -2)
Female <-- (X001 - 1)

levels(cv_tot_panel$F025)
table(cv_tot_panel$F025, useNA = "always")
cv_tot_panel$relig <- as.numeric(cv_tot_panel$F025)
table(cv_tot_panel$relig, useNA = "always")

cv_tot_panel$religd <- NA

cv_tot_panel$religd[cv_tot_panel$relig == 0] <- 0
cv_tot_panel$religd[cv_tot_panel$relig > 1 ] <- 1

table(cv_tot_panel$religd, useNA = "always")

cv_tot_panel$religd <- as.factor(cv_tot_panel$religd)
table(cv_tot_panel$religd, useNA = "always")

levels(cv_tot_panel$X007)
table(cv_tot_panel$X007, useNA = "always")
cv_tot_panel$livingtogether <- as.numeric(cv_tot_panel$X007)
table(cv_tot_panel$livingtogether, useNA = "always")

cv_tot_panel$livingtogether <- NA

cv_tot_panel$livingtogetherd[cv_tot_panel$livingtogether == 1 | cv_tot_panel$livingtogether == 2] <- 1
cv_tot_panel$livingtogetherd[cv_tot_panel$livingtogether > 3 & cv_tot_panel$livingtogether < 8] <- 0

table(cv_tot_panel$livingtogetherd, useNA = "always")

cv_tot_panel$livingtogetherd <- as.factor(cv_tot_panel$livingtogetherd)
table(cv_tot_panel$livingtogetherd, useNA = "always")

levels(cv_tot_panel$X028)
table(cv_tot_panel$X028, useNA = "always")
cv_tot_panel$paidwork <- as.numeric(cv_tot_panel$X028)
table(cv_tot_panel$paidwork, useNA = "always")

cv_tot_panel$paidwork <- NA

cv_tot_panel$paidworkd[cv_tot_panel$paidwork > 1 & cv_tot_panel$paidwork < 3] <- 1
cv_tot_panel$paidworkd[cv_tot_panel$paidwork > 4 & cv_tot_panel$paidwork < 8] <- 0

table(cv_tot_panel$paidworkd, useNA = "always")

cv_tot_panel$paidworkd <- as.factor(cv_tot_panel$paidworkd)
table(cv_tot_panel$paidworkd, useNA = "always")

model1 <- lm(as.numeric(gendernorms) ~ CNTRYunemployment, data = DatasetPaper2)
summary(model1)

model2 <- lm(as.numeric(gendernorms) ~ CNTRYunemployment + X025 + age + Female + as.factor(religd), data = DatasetPaper2)
summary(model2)

model3 <- lm(as.numeric(gendernorms) ~ CNTRYunemployment + X025 + age + Female + as.factor(religd) + paidworkd + livingtogetherd, data = DatasetPaper2)
summary(model3)


```
