---
title: "Calculate Metrics Report"
output:
  html_document: 
    toc: yes
    number_sections: false
    toc_collapse: yes
    toc_float: yes
author: "by: Siard van den Bosch"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Detailed interpretations for each network metric
```{r}
calculate_metrics_report <- function(g) {
  citaton <- function(authors, year, url) {
    paste0("(", cli::style_hyperlink(paste0(authors, ",", year), url), ")")
  }

  references <- list(
    n = citaton("Barabási", 2016, "https://networksciencebook.com"),
    m = citaton("Newman", 2010, "http://dx.doi.org/10.1093/acprof:oso/9780199206650.001.0001"),
    density = citaton("Wasserman & Faust", 1994, "https://doi.org/10.1017/CBO9780511815478"),
    path_length = citaton("Watts & Strogatz", 1998, "https://doi.org/10.1038/30918"),
    diameter = citaton("Newman", 2010, "http://dx.doi.org/10.1093/acprof:oso/9780199206650.001.0001"),
    cluster = citaton("Newman", 2003, "https://doi.org/10.1137/S003614450342480"),
    degree = citaton("Albert & Barabasi", 2002, "https://doi.org/10.1103/RevModPhys.74.47"),
    betweenness = citaton("Freeman", 1977, "https://doi.org/10.2307/3033543")
  )

  n <- c("Number of nodes (n):", igraph::vcount(g), "\n", cli::col_grey(paste0("The number of nodes indicates the overall size of the network. More nodes mean increased complexity, more relationships to analyze, and potential for larger computational resources required. Very small networks (<100 nodes) are limited in structure, while very large networks (>10,000 nodes) can be difficult to conceptualize ", references$n, ".")))

  m <- c("Number of edges (m):", igraph::ecount(g), "\n", cli::col_grey(paste0("The number of edges represents the total connections between nodes. More edges indicate higher density, more opportunities for flow between nodes, increased complexity, and more relationship weight to analyze. Low edge counts (<1000) imply sparse connectivity while high counts (>500,000) suggest an extremely interconnected network ", references$m, ".")))

  density <- c("Density:", igraph::edge_density(g), "\n", cli::col_grey(paste0("Density is the ratio of actual edges to possible edges given the number of nodes. Higher density (>0.5) means nodes are highly interconnected with many redundant ties. This can improve flow but also create congestion. Lower density (<0.2) indicates more sparse, dispersed connections between certain nodes. Very high density (>0.9) suggests almost all nodes are interconnected, while very low (<0.05) means few opportunities for node relationships ", references$density, ".")))

  path_length <- c("Average path length:", igraph::mean_distance(g), "\n", cli::col_grey(paste0("Shorter average path lengths (<4) indicate easier information diffusion across the network, with fewer steps for nodes to reach each other. Longer average lengths (>8) make communication, coordination, and overall reachability more difficult. Extremely low (<2) path lengths suggest dense local interconnectedness but lack of global reach, while extremely high (>15) path lengths indicate dispersed islands of nodes with few shortest paths ", references$path_length, ".")))


  diameter <- c("Diameter:", igraph::diameter(g), "\n", cli::col_grey(paste0("The diameter is the longest shortest path between any two nodes, indicating maximal distance to traverse the network. Small diameters (<5) tend to have dense areas that support easy navigation. Large diameters (>20) often have long chains and disjointed areas causing delays in propagation. Extremely low diameter (<3) implies essentially direct reachability between all nodes, while extremely high (>50) suggests major gaps between distant nodes ", references$degree, ".")))

  cluster <- c("Average clustering coefficient:", igraph::transitivity(g, type = "average"), "\n", cli::col_grey(paste0("Higher average clustering coefficient (>0.5) indicates nodes tend to create tightly knit groups with redundant local connections. This supports community structure. Lower clustering (<0.3) shows less cohesive group structure, with fewer common neighbors between adjacent nodes. Extremely high clustering (>0.9) indicates heavily dense overlapping groups, while extremely low (<0.1) suggests nodes have dispersed, non-clustered connections ", references$cluster, ".")))

  degree <- c("Average degree", igraph::degree(g), "\n", cli::col_grey(paste0("The degree distribution captures how connected nodes are. Right-skewed distributions indicate few high-degree hubs and many low-degree nodes. Normal distributions show evenly dispersed connections. Highly varied degrees (> 1000 max difference) imply major inequality in connectivity. Extremely low max degree (<25) indicates overall sparse connectivity, while extremely high (>5000) suggests hyper-connected hub nodes ", references$degree, ".")))

  betweenness <- c("Average betweenness centrality:", igraph::betweenness(g), "\n", cli::col_grey(paste0("Nodes with high betweenness centrality act as bridges or brokers between clusters. Low betweenness indicates decentralized pathways. A wide spread of betweenness values means certain critical nodes dominate flow. Extremely high maximum betweenness (>5000) suggests bottleneck bridges. Extremely low max (<100) implies evenly distributed traffic handling ", references$betweenness, ".")))

  all_metrics <- list(n, m, density, path_length, diameter, cluster, degree, betweenness)
  for (i in 1:length(all_metrics)) {
    cat(all_metrics[[i]])
  }
  return(all_metrics)
}
```
