---
title: "Lab journal"
author: "by: Siard van den Bosch"
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```


```{r, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("Research question"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r , echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

------------------------------------------------------------------------

::: columns
::: {.column width="100%"}
# My Lab Journal

Last compiled on `r format(Sys.time(), '%B, %Y')`

-   Week 1
    -   Formulated research question on how gender composition of academic departments relates to gender homophily in research collaborations
    -   Conducted literature review on homophily, gender inequality in academia, social networks
    -   Identified relevant theories such as tokenism that may explain greater gender divides in skewed settings
-   Week 2
    -   Collected data on faculty names, gender, titles, and contact info by webscraping department website\
    -   Queried Crossref API to retrieve metadata on faculty publications
    -   Parsed HTML table into dataframe and cleaned column names
    -   Standardized faculty names and predicted gender using R packages
    -   Difficulty handling API query errors for some author names
-   Week 3
    -   Filtered publications data to only journal articles
    -   Completed partial dates and formatted into standard structure
    -   Combined multiple affiliation columns into single column
    -   Removed missing data rows and columns
    -   Manipulated data into analysis format with author name, gender, affiliations etc.
    -   Challenges unnesting inconsistent author column lists
-   Week 4
    -   Generated node and edge data frames for the co-authorship network
    -   Calculated basic network metrics with igraph to explore topology
    -   Visualized network statically using igraph's plot function
    -   Started dynamic network modeling with RSiena but faced specification issues
    -   Goal is to model network evolution incorporating structural effects and attributes
-   Week 5
    -   Refined RSiena model specifications based on previous diagnostics
    -   Included key structural effects and covariates like gender and rank
    -   Ran models across time periods until reaching convergence
    -   Assessed model fit using goodness-of-fit diagnostics, resulted in error: need to fix
    -   Will need to evaluate additional fit statistics before finalizing
    -   Began drafting results section but too early to share due to current model issues
    -   Next steps are finalizing model specification, assessing effects, and interpreting implications
-   Week 6
    -   Added new section summarizing key concepts from Chapter 7 on common SNA methods like exponential random graph models and stochastic actor-oriented models. This provides useful background on relevant techniques.
    - Restructured paper layout into new sections - Introduction, Data Collection and Preparation, Research Design, Data, and Measures, Analysis Strategy, and Conclusion. This improves flow and organization.
    - Formatting the collaboration network data was an unexpected challenge. The RDS file format required custom code to convert into edge lists and adjacency matrices compatible with RSiena and ergm. Significant troubleshooting needed for proper data import.
    - Literature review expanded with more context on selecting appropriate SNA methods for research questions. However, balancing depth versus brevity remains tricky.
    - New section outlining analysis strategy provides clearer explanation of planned modeling approach using RSiena and ergm methods.
    - Added placeholder content to results and discussion sections for expanding later.
    - Numerous small text edits and rewording throughout for clarity and consistency. Careful proofreading is essential.
    - Overall, major enhancements to literature review, structure, data preparation in latest version compared to previous draft. Still need to finalize analyses, results and discussion.
    - Next steps are completing network models using prepared data, and interpreting results. Also expanding limitations, future directions in discussion section.
    - Despite challenges, revisions have greatly improved paper organization, flow and contextual framing. The work has progressed significantly.
  
  - Week 7
- Updated Introduction.Rmd file: 
    - Changed output format
    - Added more specifics on social network analysis and the value of examining co-authorship networks
    - Expanded on gender disparities found in recent studies
    - Added 2 additional research questions on gender differences in betweenness centrality and ego-network density
- Updated site YAML file:
    - Added new menu items linking to theory and methods pages
    - Linked new pages like gender prediction and RSiena analysis method
    - Updated titles and order of existing pages
- Added new draft analysis page demonstrating sample RSiena network model code and interpretation
<br>

------------------------------------------------------------------------
:::

::: {.column width="10%"}
:::
:::

------------------------------------------------------------------------
