---
title: "Research Questions"
output:
  html_document:
    toc: true
    number_sections: true
    highlight: kate
author: "by: Siard van den Bosch"
bibliography: references.bib
csl: apa.csl
---


## Research Questions

- $RQ_1$: What is the role of gender in triadic closure within the co-authorship network of this faculty?

Triadic closure refers to the tendency in social networks for two people who have a common acquaintance to become connected. This question seeks to uncover whether there are gender influences in this phenomenon.

- $RQ_2$: Does gender impact the betweenness centrality of researchers in the co-authorship network within this faculty?

Betweenness centrality is a measure of the extent to which a node appears on the shortest paths between other nodes. This question aims to understand whether gender plays a role in the researcher's position as bridge-makers or gatekeepers in the network.

- $RQ_3$: Female researchers will demonstrate lower triadic closure in their co-authorship ties compared to Is there a difference in the ego-network density for male and female researchers within this faculty's co-authorship network?

Ego-network density refers to the proportion of possible ties that exist between the contacts of a particular individual (the ego). This question aims to explore whether there are gender differences in the interconnectedness of collaborators.

- $RQ_4$: Are there gender-based differences in the average path length or the diameter of the co-authorship network within this faculty?

These measures relate to the average number of steps it takes to get from one member of the network to another and the longest shortest path in the network. This question seeks to understand whether gender influences the reachability and overall structure of the network.

- $RQ_5$: Does gender impact the clustering coefficient of researchers within the co-authorship network of this faculty?

The clustering coefficient measures the extent to which the collaborators of a researcher (the neighbors of a node) are collaborators with each other. This question can help understand whether there are gender differences in the tendency to form tightly knit clusters.

Each of these questions can be addressed with the `RSiena` R package, which allows for the calculation of various network metrics and the modeling of network structure and patterns. Please note that these questions might be influenced by other factors not considered in this model, like the academic rank or research interests of the researchers.

----






